Hardware Boundary Manifest Validator (AArch64/RISC-V)


#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* Public manifest structure persisted in image section .hwbound */
struct hw_boundary {
    uint64_t start;      /* base address */
    uint64_t size;       /* length in bytes (power-of-two) */
    uint32_t attrs;      /* bitfield: bit0=R, bit1=W, bit2=X, bit3=device */
    uint8_t  priv;       /* allowed privilege: 0=U,1=S,2=M or ARM EL0/EL1/EL2 */
    uint8_t  reserved[3];
    uint32_t crc32;      /* CRC32 over preceding fields for integrity */
} __attribute__((packed));

/* Symbols generated by linker to enumerate manifest entries */
extern const struct hw_boundary __hwbound_start[];
extern const struct hw_boundary __hwbound_end[];

/* Helper: check 2^k alignment */
static inline bool is_power_of_two(uint64_t x)
{
    return x && ((x & (x - 1)) == 0);
}

/* Validate and enforce boundaries; returns false on any violation */
bool enforce_hw_boundaries(void)
{
    const struct hw_boundary *it = __hwbound_start;

    for (; it < __hwbound_end; ++it) {
        /* Basic integrity checks */
        if (!is_power_of_two(it->size))
            return false;          /* size must be 2^k */
        if ((it->start & (it->size - 1)) != 0)
            return false;   /* alignment per eq.(1) */
        if (it->attrs == 0)
            return false;                     /* must permit some access */

        /*
         * Platform-specific enforcement:
         * - On AArch64 set page table entries with PXN/UXN and MAIR attributes.
         * - On RISC-V configure PTE R/W/X and user bit for U/S.
         * This loader does not change hardware here; it validates and calls platform hooks.
         */
        if (!platform_program_region(it->start, it->size, it->attrs, it->priv))
            return false;
    }

    return true;
}

/* Platform hook to be implemented per-target; returns true on success. */
/* For example, program page tables, enable MPU regions, or mark device memory. */
bool platform_program_region(uint64_t base, uint64_t size, uint32_t attrs, uint8_t priv);